"""Fix m2m tables clean

Revision ID: 1e27e9c03e21
Revises: e8c3cd7ca256
Create Date: 2025-11-16 16:53:35.434936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e27e9c03e21'
down_revision: Union[str, None] = 'e8c3cd7ca256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
